### ISSUE TITLE
JavaScript error with InitialDifferencesProtected.js

### ISSUE THREAD

**Issue by Toutouwai** [adrianbj/PageRenameOptions#3]
Hi Adrian,

On one site I am seeing a JS error in the browser console coming from InitialDifferencesProtected.js when a page is opened in Page Edit:

![2023-09-01_171243](https://github.com/adrianbj/PageRenameOptions/assets/1538852/e0050316-063f-4126-9e17-3b5f247f229e)

The page in question has the title field locked so there's no input element inside. This could perhaps be handled like this:

```js
$(document).ready(function() {
    var $input = $(".InputfieldPageTitle input[type=text]");
    if($input.length && typeof InputfieldPageName !== 'undefined') initialTitleConverted = InputfieldPageName.sanitize($input.val());
});
```

**Comment by adrianbj** [comment]
Thanks @Toutouwai for the fix. It's available in the current version.
